label: Tags
status: wip

variants:
  - name: default
    label: Info
    context:
      label:
        classes: "usa-tag"

  - name: big
    label: Big
    context:
      label:
        classes: "usa-tag usa-tag--big"
