label: Footer
status: ready

context:
  attributes: {}
  footer_phone: 1-800-222-2225
  footer_email: niaic@nia.nih.gov
  footer_slim: true
  display_footer_primary: true
  display_footer_secondary: true
  display_footer_agency: true
  footer_style: slim
  facebook: 'https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2FNIHAging%2F'
  twitter: 'https://twitter.com/NIHAging'
  youtube: 'https://www.youtube.com/user/NatlInstituteOnAging'
  linkedin: 'https://www.linkedin.com/company/national-institute-on-aging/'
  instagram: 'javascript:void()'
  rss: 'javascript:void()'
  contact_center: Agency Contact Center
  footer_agency_name: Agency
  footer_agency_description: A federal government website managed by the National Institute on Aging, National Institutes of Health, U.S. Department of Health and Human Services.
  footer_agency_logo: '/images/logo_nih-nia_min.svg'
  uswds_images: /fractal/img/
  page:
    footer_menu: '@@menus--footer'

variants:
  - name: default
    label: Default
  - name: big
    context:
      footer_style: big
      phone: '1-800-555-5555'
      email: 'info@agency.gov'
      footer_slim: false
      page:
        footer_menu: '@@menus--footer-big'
  - name: medium
    context:
      footer_style: medium
      phone: '1-800-555-5555'
      email: 'info@agency.gov'
      footer_slim: false
      page:
        footer_menu: '@@menus--footer-medium'
  - name: non-topics
    context:
      footer_style: medium
      phone: '1-800-555-5555'
      email: 'info@agency.gov'
      footer_slim: false
      page:
        footer_menu: '@@menus--regular-footer'


