label: Summary box
status: wip
context:
  items:
  - >
    If you are under a winter storm warning,
          <a class="usa-summary-box__link" href="javascript:void(0);">find shelter</a>
          right away.
  - >
    Sign up for
          <a class="usa-summary-box__link" href="javascript:void(0);">your community’s warning system</a>.
  - >
    Learn the signs of, and basic treatments for,
          <a class="usa-summary-box__link" href="javascript:void(0);">frostbite</a>
          and
          <a class="usa-summary-box__link" href="javascript:void(0);">hypothermia</a>.
  - >
    Gather emergency supplies for your
          <a class="usa-summary-box__link" href="javascript:void(0);">home</a>
          and your
          <a class="usa-summary-box__link" href="javascript:void(0);">car</a>.
